# Generated by Django 4.1 on 2022-09-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/districts')),
                ('text', models.TextField(max_length=5000)),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'Области',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, default='User', max_length=20, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('news', models.TextField(max_length=2000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/news')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Towns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/cities')),
                ('text', models.TextField(max_length=5000)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
    ]
