# Generated by Django 4.1 on 2022-11-27 17:13

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', ckeditor.fields.RichTextField(default='', verbose_name='Описание страницы "О проекте"')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Пост 'О проекте'",
                'verbose_name_plural': "Посты 'О проекте'",
            },
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='Область')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/districts', verbose_name='Фотография')),
                ('desk', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('area_slug', models.SlugField(max_length=160, primary_key=True, serialize=False, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'Области',
            },
        ),
        migrations.CreateModel(
            name='Towns',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='Город')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/cities', verbose_name='Фотография для превью')),
                ('short_info', models.TextField(default='', max_length=2000, verbose_name='Короткое описание, для превью')),
                ('watch', ckeditor.fields.RichTextField(default='', verbose_name='Описание достопримечательностей')),
                ('eat', ckeditor.fields.RichTextField(default='', verbose_name='Описание мест общепита, где можно перекусить')),
                ('sleep', ckeditor.fields.RichTextField(default='', verbose_name='Список и описание мет для отдыха - гостиниц, кемпингов, хостелов')),
                ('town_slug', models.SlugField(max_length=160, primary_key=True, serialize=False, unique=True, verbose_name='URL')),
                ('district', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guide.districts', verbose_name='Область страны')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='UserTowns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False, verbose_name='В публикации')),
                ('watch', ckeditor.fields.RichTextField(default='', verbose_name='Описание достопримечательностей')),
                ('eat', ckeditor.fields.RichTextField(default='', verbose_name='Описание мест общепита, где можно перекусить')),
                ('sleep', ckeditor.fields.RichTextField(default='', verbose_name='Список и описание мест для отдыха - гостиниц, кемпингов, хостелов')),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор публикации')),
                ('town', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guide.towns', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Публикации пользователей',
                'verbose_name_plural': 'Публикации пользователей',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок новости')),
                ('short_news', models.TextField(blank=True, default='Подробности внутри', max_length=1000, null=True, verbose_name='Короткое описание новости, превью')),
                ('news', ckeditor.fields.RichTextField(verbose_name='Текст новости')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/news', verbose_name='Иллюстрация')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='URL')),
                ('author', models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
