# Generated by Django 4.1 on 2022-09-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_towns_area_alter_news_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towns',
            name='area',
            field=models.CharField(choices=[('brest_district', 'Брестская область'), ('vitebsk_district', 'Витебская область'), ('gomel_district', 'Гомельская область'), ('grodno_district', 'Гродненская область'), ('minsk_district', 'Минская область'), ('mogilev_district', 'Могилевская область')], default='brest_district', max_length=16),
        ),
    ]
