# Generated by Django 4.1 on 2022-09-29 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_alter_towns_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='towns',
            name='area',
        ),
    ]
