# Generated by Django 4.1 on 2022-10-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_alter_districts_desk_alter_news_news_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='short_news',
            field=models.TextField(default='Подробности внутри', max_length=1000, verbose_name='Короткое описание новости, превью'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата публикации'),
        ),
    ]
