# Generated by Django 4.1 on 2022-10-02 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0006_alter_districts_district_alter_districts_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='towns',
            name='area',
        ),
        migrations.AddField(
            model_name='towns',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guide.districts'),
        ),
    ]
