# Generated by Django 4.1 on 2022-10-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0007_remove_towns_area_towns_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='districts',
            old_name='text',
            new_name='desk',
        ),
        migrations.RenameField(
            model_name='districts',
            old_name='district',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='towns',
            old_name='town',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='towns',
            name='text',
        ),
        migrations.AddField(
            model_name='towns',
            name='full_desk',
            field=models.TextField(default='', max_length=5000, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='towns',
            name='short_info',
            field=models.TextField(default='', max_length=2000, verbose_name='Короткое описание'),
        ),
    ]
