# Generated by Django 4.1 on 2022-10-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0008_rename_text_districts_desk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='', max_length=10000, verbose_name='Описание страницы "О проекте"')),
            ],
            options={
                'verbose_name': "Пост 'О проекте'",
                'verbose_name_plural': "Посты 'О проекте'",
            },
        ),
        migrations.AlterField(
            model_name='towns',
            name='full_desk',
            field=models.TextField(blank=True, default='', max_length=5000, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='towns',
            name='short_info',
            field=models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='Короткое описание'),
        ),
    ]
