# Generated by Django 4.1 on 2022-10-10 22:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0010_about_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='towns',
            name='full_desk',
        ),
        migrations.AddField(
            model_name='towns',
            name='eat',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Описание мест общепита, где можно перекусить'),
        ),
        migrations.AddField(
            model_name='towns',
            name='sleep',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Список и описание мет для отдыха - гостиниц, кемпингов, хостелов'),
        ),
        migrations.AddField(
            model_name='towns',
            name='watch',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=5000, null=True, verbose_name='Описание достопримечательностей'),
        ),
        migrations.AlterField(
            model_name='districts',
            name='desk',
            field=ckeditor.fields.RichTextField(max_length=5000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news',
            field=ckeditor.fields.RichTextField(max_length=2000, verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='towns',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/cities', verbose_name='Фотография для превью'),
        ),
        migrations.AlterField(
            model_name='towns',
            name='short_info',
            field=models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='Короткое описание, для превью'),
        ),
    ]
