# Generated by Django 4.1 on 2022-10-12 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0013_alter_usertowns_options_usertowns_is_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertowns',
            name='user',
        ),
        migrations.AddField(
            model_name='usertowns',
            name='author',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='usertowns',
            name='district',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guide.districts'),
        ),
    ]
