# Generated by Django 4.1 on 2022-10-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0014_remove_usertowns_user_usertowns_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertowns',
            name='town',
            field=models.CharField(default='', max_length=50, verbose_name='Город'),
        ),
    ]
