# Generated by Django 4.1 on 2022-10-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/news', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='User.is_authenticated', max_length=200, verbose_name='Автор'),
        ),
    ]
